spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true

logging:
  level:
    academy-devdojo: debug
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: ON_PARAM #?trace=true
  tomcat:
    threads:
      max: 20